export const BOX = "w-full h-10 border-2 border-purple-500"
export const FULL_SCREEN = "calc(100vh-90px)"
export const ACCENT_COLOUR = "#ADD8E6"
export const BG_LIGHT_COLOR = "#dee2e6"
export const BG_DARK_COLOR = "#343a40"